import sys
import numpy as np
import os, sys, time, shutil
import h5py
import matplotlib.pyplot as plt
import glob
from LEF_paths_gen import make_loading_profile

def load_data(folder_path, L):
    """
    Loads all the data saved in the .h5 files generated by LEF_paths_gen
    """
    files = sorted(glob.glob(os.path.join(folder_path, '*.h5')))
    # Storage lists
    all_l_sites             = []
    all_r_sites             = []    
    all_ts                  = [] 
    all_loading_site_probs  = []
    all_lef_lifetimes       = []

    for f in files:
        # Starting the accumulated loading-site counter
        loading_probs_accum = np.zeros(L, dtype=np.float64)
        with h5py.File(f, 'r') as hf:
            all_l_sites.append(hf['l_sites'][:])
            all_r_sites.append(hf['r_sites'][:])
            all_ts.append(hf['ts'][:])
            all_lef_lifetimes.append(hf['lef_lifetimes'][:])
            all_loading_site_probs.append(np.array(hf["loading_site_probs"][:]))

    # Convert to numpy arrays
    all_l_sites             = np.concatenate(all_l_sites)
    all_r_sites             = np.concatenate(all_r_sites)
    all_ts                  = np.concatenate(all_ts)
    # Normalization of probabilities
    loading_probs_accum     = np.sum(all_loading_site_probs, axis=0)
    loading_probs_accum     = loading_probs_accum / loading_probs_accum.sum()
    all_lef_lifetimes       = np.concatenate(all_lef_lifetimes)

    return (all_l_sites, all_r_sites, all_ts, loading_probs_accum, all_lef_lifetimes)

def chip_dist(folder_path, L, scale_log = False):
    """
    Compute ChIP-seq profile from LEF paths data.
    Input:
        The folder path containing the .h5 files
    """
    data_l, data_r, data_ts, data_loading_sites, data_lifetimes = load_data(folder_path,L)
    # Compute the ChIP-seq profile using the loaded data
    # Flatten the array and remove detached sites (-1)
    l_valid_sites = data_l[data_l >= 0].flatten()
    r_valid_sites = data_r[data_r >= 0].flatten()

    all_sites = np.concatenate((l_valid_sites,r_valid_sites))

    # Count occurrences at each site from 0 to L-1
    # np.bincount will count frequencies of values efficiently
    chip_seq_counts = np.bincount(all_sites, minlength=L)

    # Optional: normalize to get occupancy per time point
    chip_seq_profile = chip_seq_counts / chip_seq_counts.sum()  # or / (T*N) if you want full density

    np.savez_compressed(os.path.join(folder_path, f"sim_chip_seq_profile_L{L}.npz"), profile=chip_seq_profile)

    plt.figure(figsize=(8, 4))
    plt.plot(np.arange(L), chip_seq_profile, drawstyle='steps-mid')
    plt.title("Simulated ChIP-Seq profile from loop extruders")
    plt.xlabel("Genomic position (lattice site)")
    plt.ylabel("Average occupancy")
    if scale_log:
        plt.yscale("log")
    plt.grid(True, axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(os.path.join(folder_path, "sim_chip_seq_profile.png"), dpi=500)
    plt.show()


def lifetimes_dist(folder_path, L):
    """
    Display life-time distribution for all the simulations.
    """
    data_l, data_r, data_ts, data_loading_sites, data_lifetimes = load_data(folder_path, L)
    data_lifetimes = np.array(data_lifetimes, dtype=np.float64)
    np.savez_compressed(os.path.join( folder_path, "sim_lifetime_dist"), profile = data_lifetimes)

    # Compute mean
    mean_val = np.mean(data_lifetimes)

    # Plot histogram
    plt.figure(figsize=(8, 5))
    plt.hist(
        data_lifetimes,
        bins=50,
        density=True,          # normalize to probability distribution
        alpha=0.7,
        color="tomato",
        edgecolor="black"
    )

    # Add vertical line at mean
    plt.axvline(mean_val, color="red", linestyle="--", linewidth=2, label=f"Mean = {mean_val:.2f}")

    # Annotate the mean value near the line
    plt.text(mean_val, plt.ylim()[1]*0.9, f"{mean_val:.2f}",
            color="red", fontsize=12, ha="center")

    # Labels and styling
    plt.title("Distribution of LEF Lifetimes")
    plt.xlabel("Lifetime")
    plt.ylabel("Probability Density")
    plt.grid(True, linestyle="--", alpha=0.6)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(folder_path, "sim_lifetime_distribution.png"), dpi=600)
    plt.show()

def loading_site_dist(folder_path, L, ori = 0.5, A = 1.0, d = -50, shift = 0):
    """
    Computes loading-site distribution of the input vs the resulting simulated one
    """
    data_l, data_r, data_ts, data_loading_sites, data_lifetimes = load_data(folder_path, L)
    loading_site_probs = np.array(data_loading_sites)
    # Saving Data
    np.savez_compressed(os.path.join( folder_path, f"sim_loading_sites_probs_L{L}"), profile = loading_site_probs)
    # Preparing Figure
    plt.figure(figsize=(10, 4))
    trash, input_profile = make_loading_profile(L, ori=ori, A=A, d=d, shift=shift)
    # Plot input profile (background, transparent)
    plt.plot(np.arange(L), input_profile, color='gray', alpha=0.7, label='Input loading-site profile', linewidth=3)

    # Plot resulting distribution (foreground)
    plt.plot(np.arange(L), loading_site_probs, color='blue', drawstyle='steps-mid', label='Simulated loading-site distribution', linewidth=0.5)

    plt.title("Loading site distribution vs input profile")
    plt.xlabel("Site i")
    plt.ylabel("Probability")

    xticks = np.linspace(0, L-1, 10, dtype=int)
    plt.xticks(xticks)
    plt.grid(True, axis='y', linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(folder_path, "sim_loading_site_distribution.png"), dpi=600)
    plt.show()

def loop_size_dist(folder_path, L):
    # Loop size distribution
    data_l, data_r, data_ts, data_loading_sites, data_lifetimes = load_data(folder_path, L)
    #l_sites = np.array(data_l, dtype=np.float64)
    #r_sites = np.array(data_r, dtype=np.float64)

    # Flatten the array and remove detached sites (-1)
    l_valid_sites = data_l[data_l >= 0].flatten()
    r_valid_sites = data_r[data_r >= 0].flatten()

    # Calculate loop sizes with PBC (if l_leg > r_leg, it because it went around the origin)
    loop_sizes = (r_valid_sites - l_valid_sites)%L
    # Saving Data
    np.savez_compressed(os.path.join( folder_path, f"sim_loop_sizes_L{L}"), profile = loop_sizes)
    # Max loop sizs sets the number of bins
    max_loop_size = np.max(loop_sizes[loop_sizes >= 0])+1
    loop_dist  = np.bincount(loop_sizes[loop_sizes >= 0], minlength=max_loop_size)
    loop_dist_normalized = loop_dist / loop_dist.sum()  # Normalize to get probability distribution


    plt.figure(figsize=(8, 4))
    plt.plot(np.arange(max_loop_size), loop_dist_normalized, drawstyle='steps-mid')
    plt.title("Simulated Loop Size Distribution from loop extruders")
    plt.xlabel("Loop Size")
    plt.ylabel("Probability")
    plt.grid(True, axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(os.path.join(folder_path, "sim_loop_size_distribution.png"), dpi=600)
    plt.show()